/**
 * A single-source file containing rich contextual notes for Soochi entries.
 * Each entry gets a "why it matters + how to use it" note.
 *
 * This is deliberately written as a data structure, not a generation script,
 * so notes can be reviewed and improved over time.
 */

export const NOTES = {

  // ================================================================
  // ORIGINAL ENTRIES that had no body text
  // ================================================================

  "aser-centre": `ASER (Annual Status of Education Report) is India's largest citizen-led household survey, reaching over 600,000 children across nearly every rural district. Unlike school-leaving exams, ASER tests basic reading and arithmetic — and the results, consistently sobering, have reshaped India's education policy debate for two decades. The survey is unusual in being conducted by volunteers (mostly college students) rather than professional enumerators, which gives it both scale and public engagement that top-down surveys lack. ASER Centre also runs the ASER-based assessment tools used by several state governments. If you need to know whether Indian children are actually learning — as opposed to just being enrolled — this is the indispensable source.`,

  "global-forest-watch": `Global Forest Watch (GFW), run by the World Resources Institute, is the closest thing to a real-time dashboard for the world's forests. It combines satellite data from GLAD (University of Maryland) with national forest statistics, concession maps, and user-submitted reports. For India, GFW is most useful for tracking forest loss alerts — you can subscribe to near-real-time notifications for a specific district, protected area, or watershed, and receive an alert when tree cover loss is detected. This makes it a powerful accountability tool: researchers, journalists, and activists can independently verify deforestation claims rather than relying solely on government FSI biennial reports. The data is free, open, and accessible through both the web platform and an API.`,

  "imf-data": `The IMF Data portal is the primary access point for the Fund's macroeconomic and financial statistics. For India researchers, the most useful datasets are the World Economic Outlook (macroeconomic projections updated twice yearly), the International Financial Statistics (exchange rates, reserves, money supply, interest rates — monthly data going back to 1948 for India), and the Government Finance Statistics (revenue, expenditure, debt). The Direction of Trade Statistics maps India's bilateral trade flows. What makes IMF Data distinctive is its cross-country comparability — the same methodology applied to 190+ countries, making India's macro indicators directly comparable with peers. All datasets are accessible through the IMF Data API and bulk downloads. Free registration required for some series.`,

  "indiaspend": `IndiaSpend was India's first data journalism initiative, founded in 2011 by journalist Govindraj Ethiraj. It pioneered the model of using public datasets — government surveys, budget documents, RTI responses, academic research — to produce explanatory journalism on health, education, environment, agriculture, and governance. For researchers and journalists, IndiaSpend is valuable not just as a news source but as a demonstration of which Indian datasets can be fruitfully mined for stories. Their archives, going back over a decade, contain thousands of data-driven explainers and investigations. IndiaSpend also runs fact-checking (FactChecker.in) and training programmes for data journalism.`,

  "india-water-portal": `India Water Portal is one of the oldest and most comprehensive open knowledge platforms on water in India. Founded by Arghyam, it aggregates data, research, news, and community knowledge on rainfall, groundwater, surface water, water quality, irrigation, drinking water, sanitation, and water policy. It is particularly useful for finding historical context — the portal's archive of articles, case studies, and datasets goes back nearly two decades. For researchers and practitioners, it functions as both a knowledge library and a community of practice. The portal also hosts interactive maps and visualisations of water data that are more accessible than the raw government portals they draw from.`,

  "india-wris": `India-WRIS (Water Resources Information System) is the government's central water data platform, jointly run by the Central Water Commission and ISRO. It provides rainfall, reservoir levels, groundwater depth, river discharge, water quality, and evapotranspiration data across India, much of it at basin and sub-basin scales. The platform includes both a web GIS for map-based exploration and downloadable datasets. For researchers, the major value is having multiple water dimensions — surface water, groundwater, quality, and climate — in one place, with consistent spatial frameworks. The data feeds into water resource assessments, drought monitoring, flood management, and inter-state water dispute analysis.`,

  "kobotoolbox": `KoboToolbox is the most widely used open-source data collection platform in the humanitarian and development sectors. Developed by the Harvard Humanitarian Initiative, it lets organisations build complex survey forms, collect data offline on mobile devices, and manage submissions through a clean web interface. For Indian civil society, Kobo has become the de facto standard for household surveys, needs assessments, monitoring and evaluation, and field research — largely because it is free, works without internet connectivity, and handles multiple languages (including most Indian languages). The platform is used by thousands of Indian NGOs, research organisations, and government agencies. Data can be exported in multiple formats and connected to analysis tools.`,

  "open-budgets-india": `Open Budgets India (OBI) is the single most comprehensive source for machine-readable Indian budget data. While the Union Budget and state budgets are publicly available as PDFs, OBI converts them into structured, analysable datasets. It covers Union Budget expenditures, state budgets, municipal budgets, and scheme-level allocations. For researchers, OBI solves the fundamental problem of Indian fiscal analysis: budget documents are designed for parliamentary presentation, not quantitative research. OBI's cleaned datasets let you compare allocations across years, across states, and across schemes without spending weeks cleaning PDF-scraped data. The platform is maintained by the Centre for Budget and Governance Accountability (CBGA).`,

  "undp-hdr": `The UNDP Human Development Reports provide the Human Development Index and its components — life expectancy, education (mean and expected years of schooling), and GNI per capita — for every country from 1990 onwards. Beyond the headline HDI, the data portal includes the Inequality-adjusted HDI, Gender Development Index, Gender Inequality Index, and Multidimensional Poverty Index. For India researchers, the key value is the long time series: you can track India's HDI trajectory against peers (Bangladesh, China, Indonesia, Brazil) over three decades, or examine subnational HDI estimates published for Indian states. The data is freely downloadable and well-documented, making it a standard reference for any discussion of India's development progress.`,

  "unesco-uis": `The UNESCO Institute for Statistics is the official global source for education statistics. For India, it provides comparable data on school enrolment rates (primary, secondary, tertiary), completion rates, literacy, education expenditure as a share of GDP, pupil-teacher ratios, and gender parity indices. The key advantage over India's own education statistics (UDISE+, AISHE) is cross-country comparability: UIS data applies consistent definitions across 200+ countries, so you can reliably compare India's education indicators with other countries. The database also covers science, technology, innovation, and culture statistics. Free API and bulk download access.`,

  "unicef-data": `UNICEF Data is the organisation's statistical portal, providing indicators on children and women across 190+ countries. For India, the most important datasets cover child mortality (under-5, infant, neonatal), maternal health, nutrition (stunting, wasting, anaemia), education (out-of-school children), child marriage, birth registration, and water/sanitation access. UNICEF's data draws from household surveys (DHS/MICS), UN agencies, and government statistics, with a strong emphasis on data quality and methodological transparency. The data is freely downloadable and accessible through an API. The India country profile aggregates the most-requested indicators in one place.`,

  "vidhi-centre-for-legal-policy": `Vidhi Centre for Legal Policy is an independent think-tank that does legal research to improve governance in India. Its work spans judicial reforms, regulatory design, municipal law, environmental law, financial regulation, and public health law. For researchers and civic technologists, Vidhi's most important public artefacts are practical legal tools: the SARAL Manual for plain-language legislative drafting, the End-of-Life Care Toolkit with model legal documents, and the SARAL platform for simplifying legal language. Vidhi also publishes detailed legal analyses of proposed legislation, making it a key resource for understanding how laws are actually designed and implemented. It has offices in Delhi and Bengaluru.`,

  "who-gho": `The WHO Global Health Observatory is the World Health Organization's statistical portal, providing over 1,000 health indicators for 194 member states. For India, the most useful datasets cover mortality (life expectancy, cause-of-death, maternal and child mortality), disease burden (TB, malaria, HIV, NCDs), health systems (health workforce, hospital beds, health expenditure), risk factors (tobacco, alcohol, obesity), and environmental health (air pollution, water/sanitation). The data is free, well-documented, and accessible through an API. The GHO's strength is its cross-country comparability — every indicator uses the same definitions and methodology, making India comparable with any other country in the world.`,

  "india-data-portal": `India Data Portal (IDP), run by ISB's Bharti Institute of Public Policy, is one of the most useful Indian resources that remains surprisingly under-known. It aggregates and standardises public datasets from across the Indian government — agriculture (mandi prices, crop production), financial inclusion (banking penetration), elections (candidate affidavits, results), health (NFHS), and education (UDISE) — into a common, analysis-ready format. For researchers who don't want to spend their lives cleaning government spreadsheets, IDP is a godsend. It provides visualisation tools, APIs, and pre-computed summary statistics. The portal also publishes analytical articles demonstrating how to use the data for policy research.`,

  "un-data": `UNdata is the UN system's unified statistical portal, providing a single search interface across 35 UN databases — from population and national accounts to trade and energy. For India researchers, it aggregates country-level data from WHO, UNESCO, ILO, FAO, UNIDO, World Bank, IMF, and the UN Statistics Division. The key value is convenience: instead of visiting a dozen agency-specific portals, you can get demography, economy, health, education, and environment data for India from a single query. Data is downloadable in multiple formats. Particularly useful for quick cross-country comparisons and for finding data from smaller UN agencies that are harder to discover individually.`,

  // ================================================================
  // IMPORTANT DATA SOURCES that should have richer notes
  // ================================================================

  "data-gov-in": `data.gov.in is India's Open Government Data platform, launched in 2012 under the National Data Sharing and Accessibility Policy. It currently hosts tens of thousands of datasets from central ministries, state governments, and district administrations — covering agriculture, health, education, transport, water, energy, and hundreds of other topics. Many datasets are exposed through documented APIs, and the platform uses the CKAN open-source data portal software, which means the API is well-standardised. The quality is uneven — some datasets are meticulously maintained, others are outdated or incomplete — but the sheer breadth makes it indispensable. For journalists and civic technologists, data.gov.in is the first place to check whether the government already publishes a dataset before filing an RTI.`,

  "eci": `The Election Commission of India's data portal is one of the most comprehensive electoral data resources in the world. It publishes full results for every Lok Sabha and Vidhan Sabha election (candidate votes, party totals, constituency maps), electoral rolls with demographic breakdowns, candidate affidavits (assets, criminal cases, education), and detailed statistical reports on voter turnout by gender, age, and constituency. For researchers, the ECI data enables analysis of electoral behaviour, party system change, money in politics, and representation over multiple decades. The candidate affidavit data alone has supported hundreds of academic papers and investigative journalism projects. Most data is available as downloadable PDFs and CSVs.`,

  "open-city": `OpenCity is Oorvani Foundation's urban data commons platform, designed to make Indian city data accessible and usable. It hosts datasets on city budgets, municipal finance, ward boundaries, mobility, public services, and environmental indicators — structured around the needs of civic researchers, journalists, and activists rather than government reporting requirements. OpenCity also runs data jams and community data collection events, building a practice of collaborative urban data stewardship. For anyone working on Indian urban issues, OpenCity provides both data and a model for how civic data infrastructure should work: open, maintainable, and connected to community action.`,

  "our-world-in-data": `Our World in Data (OWID), based at the University of Oxford, is one of the most important public data resources of the modern era. It takes complex global datasets — from the UN, World Bank, WHO, and academic research — and presents them as clear, interactive charts with thorough methodological notes. For India, OWID provides pre-processed, ready-to-use data on nearly every development topic: poverty, health, education, energy, environment, and demographics. What makes OWID special is that every chart links to the underlying data (downloadable as CSV) and the original source, making it both a discovery tool and a reliable citation chain. The entire platform is open-source and all data is CC BY licensed.`,

  "datameet": `DataMeet is a community of data enthusiasts, researchers, and civic technologists who work on making Indian public data more accessible and usable. They run meetups, workshops, and hackathons across Indian cities, and maintain a repository of cleaned and structured Indian datasets — often taking messy government data and making it analysis-ready. For anyone getting started with Indian public data, DataMeet is the community to connect with: the members know where to find data, how to clean it, and what its limitations are. The community is volunteer-run, open to all, and operates primarily through its Google Group, GitHub repositories, and in-person events.`,

  "ndap": `NITI Aayog's National Data & Analytics Platform (NDAP) is probably the most useful Indian data resource that is still not nearly well-known enough. It brings together datasets from across the government — agriculture, health, education, infrastructure, demography, economy — into a single platform with consistent formatting, a unified search interface, and built-in visualisation tools. For researchers, NDAP dramatically reduces the time spent finding, downloading, cleaning, and merging datasets from different ministries. The platform allows side-by-side comparison of indicators across states and districts, and supports data downloads in multiple formats. NDAP represents the government's most serious attempt to bridge the gap between publishing data and making it actually usable.`,

  "upag": `UPAG (Unified Portal for Agricultural Statistics) is the government's attempt to bring India's fragmented agricultural data into one place. It integrates crop area, production, and yield statistics from the Directorate of Economics and Statistics, mandi price data from AGMARKNET, and other agricultural datasets into a unified platform. For researchers, UPAG addresses a longstanding frustration: agricultural data in India is scattered across multiple portals with inconsistent formats and identifiers. UPAG provides a single query interface and consistent data schema across commodities, states, and time periods. The portal is part of the broader push toward a unified agricultural data ecosystem.`,

  "nrega-public-data": `MGNREGA's public data portal is one of the most remarkable government transparency initiatives in the world. It publishes real-time, transaction-level data on India's rural employment guarantee programme: job cards issued, works undertaken, muster rolls (who worked, for how many days), and payments made — all down to the Gram Panchayat level. For researchers, this has supported an enormous body of independent work on rural labour markets, programme implementation, corruption, gender equity, and climate adaptation. The data is updated daily and accessible through both the web dashboard and programme APIs. MGNREGA's public data infrastructure is often held up as a model for how other government schemes should report.`,

  "egramswaraj": `eGramSwaraj is a hidden gem of Indian civic data. At the Gram Panchayat level — India's most local tier of government — you can find development plans, budget allocations, actual expenditures, work progress with geo-tagged photographs, and audit reports. The platform links planning, financial management, and physical progress monitoring in one system. For researchers, eGramSwaraj provides an unprecedented window into how public money flows to and through India's 2.5 lakh Gram Panchayats. It deserves a giant "you probably didn't know this existed" badge. The related Gram Manchitra platform provides the spatial complement with infrastructure mapping at Panchayat scale.`,

  "jal-jeevan-mission-dashboard": `The Jal Jeevan Mission (JJM) Dashboard tracks India's programme to provide functional household tap connections to every rural household — one of the largest drinking water interventions in history. The dashboard provides real-time data at state, district, block, and habitation level: households connected, tap connection coverage percentage, water quality testing results, village certification status, and scheme finances. For researchers, JJM data enables analysis of infrastructure rollout, state-level implementation capacity, water quality challenges, and the relationship between piped water access and health outcomes. The dashboard is unusually granular and frequently updated for an Indian government programme.`,

  "nfhs": `The National Family Health Survey is India's Demographic and Health Survey — one of the largest household surveys in the world, covering 600,000+ households in its fifth round (2019-21). It provides district-level estimates for health, nutrition, fertility, family planning, maternal and child health, adult health, domestic violence, and women's empowerment indicators. For researchers, the critical distinction is between NFHS fact sheets (pre-computed indicator tables available on the website) and the microdata (anonymised individual and household-level records available through the DHS Program with registration). The microdata enables custom analysis — cross-tabulations, regressions, spatial analysis — that goes far beyond what the published reports provide. NFHS-5 data is available for 707 districts across 36 states and UTs.`,

  "ncrb": `The National Crime Records Bureau's Crime in India report is the canonical source for crime statistics in India. Published annually, it provides state and district-level data on IPC crimes (murder, rape, kidnapping, theft, rioting), SLL crimes, crimes against women, children, SC/ST, cyber crimes, accidental deaths, and suicides. For researchers, the data enables analysis of crime patterns, police effectiveness, and criminal justice system performance — though with well-documented limitations around underreporting, misclassification, and political interference in data collection. The data is available as PDF reports and increasingly as downloadable tables. Used by researchers, journalists, and policy analysts despite (and sometimes because of) its limitations.`,

  "njdg": `The National Judicial Data Grid (NJDG) is a live dashboard showing case pendency and disposal across India's district and subordinate courts, and increasingly the High Courts. You can see exactly how many cases are pending in each court complex, broken down by case type (civil/criminal), age (0-1 year, 1-3, 3-5, 5-10, 10+ years), and stage of proceedings. For researchers and journalists, NJDG provides real-time evidence for arguments about judicial delays and backlog — and for tracking whether reform efforts are working. The Supreme Court's version (SC-NJDG) was launched more recently. Both are part of the eCourts project and are publicly accessible without registration.`,

  "parivesh": `PARIVESH (Pro-Active and Responsive facilitation by Interactive, Virtuous and Environmental Single-window Hub) is the government's online portal for environmental, forest, and wildlife clearances. It publishes every clearance application, the associated documents (EIA reports, public hearing records, expert committee minutes), and the final decision. For researchers and journalists, PARIVESH is the primary tool for tracking what is being built through India's forests, coasts, and ecologically sensitive areas — and for holding the clearance process accountable. The data enables analysis of clearance timelines, approval rates by state and sector, and compliance with environmental conditions. An essential transparency infrastructure, though the interface can be challenging.`,

  "survey-of-india-maps": `The Survey of India's Online Maps Portal provides official administrative boundaries, topographic maps, road and railway networks, hydrological features, terrain data, and village boundary products. For researchers and civic technologists, these are the authoritative spatial reference layers for any mapping work in India. The portal provides both downloadable data products and web map services (OGC-compliant). Particularly useful are the administrative boundary shapefiles (state, district, sub-district, village) which are the standard reference for spatial analysis and map-making. Some products require purchase or registration; others are freely downloadable.`,

  "development-data-lab": `Development Data Lab (DDL) is a US-based research group that publishes the SHRUG (Socioeconomic High-resolution Rural-Urban Geographic) platform — an open geographic dataset linking Indian census data, economic census data, night-lights satellite data, and other spatial data at the village, town, and ward level. For researchers, SHRUG is a transformative resource: it provides a consistent spatial framework spanning 1990-2020, enabling panel data analysis of economic development, urbanisation, and public service delivery at much finer resolution than state or district aggregates. All data is freely downloadable and well-documented. DDL also publishes working papers demonstrating how to use the data for policy-relevant research.`,

  "data-for-india": `Data for India, founded by data journalist Rukmini S, is one of the best starting points for understanding Indian development data. It presents curated, well-explained charts and underlying data on demography, economy, health, and social indicators — designed for people who are not statisticians but need reliable numbers. What makes DFI distinctive is its rigorous approach to data provenance: every chart links to the original source, explains what the data does and doesn't measure, and contextualises limitations. The site is particularly useful for journalists, students, and policy professionals who need defensible national-level numbers quickly and want to understand how they were constructed, not just cite them.`,

  "moSPI-mcp": `The MoSPI MCP (Model Context Protocol) Server is an innovative experiment by the Ministry of Statistics and Programme Implementation to make 27 official Indian statistical datasets queryable through natural language. Instead of navigating download pages and documentation, a researcher can ask an AI assistant questions like "what was rural female labour force participation in Bihar in 2022-23" and get data retrieved from the PLFS microdata. The server covers national accounts, CPI, IIP, PLFS, HCES, and other core MoSPI datasets. It represents an important step toward making government data accessible to non-specialist users. The source code is open and available on GitHub.`,

  "nfsa-dashboard": `The NFSA (National Food Security Act) and Public Distribution Dashboard tracks the world's largest food safety net programme. It provides real-time data on ration cards, beneficiaries, fair-price shops, foodgrain allocation, offtake, distribution, and portability under the One Nation One Ration Card system. For researchers, the dashboard enables analysis of PDS coverage, leakages (by comparing allocation to offtake to distribution), state-level implementation quality, and the gender dimension (women-headed ration cards). The granularity — down to district and sometimes FPS level — makes it possible to identify implementation gaps that aggregate national statistics would hide.`,

  "ppac-petroleum-statistics": `PPAC (Petroleum Planning & Analysis Cell) publishes the definitive data on India's petroleum and natural gas sector: domestic production, imports, refining, consumption by product (petrol, diesel, LPG, ATF, naphtha), prices (retail and wholesale), taxes, and industry infrastructure. For researchers, PPAC data is essential for understanding India's energy transition — the growth of petroleum consumption, the shifting fuel mix, the import dependency, and the fiscal contribution of petroleum taxes. Monthly reports provide the most current data, while annual reports and atlases provide the long-term perspective. The data is free and downloadable.S`,

  "rbi-dbie": `The RBI's Database on Indian Economy (DBiE) is the central bank's statistical warehouse — the authoritative source for data on money supply, banking aggregates, credit and deposits, financial markets, external sector (balance of payments, exchange rates, foreign reserves), prices (CPI, WPI), and public finance. For researchers, DBiE provides long time series (many going back to the 1950s) with consistent definitions and well-documented methodology. The interactive portal allows custom queries, charting, and data downloads. DBiE is maintained by the RBI's Department of Statistics and Information Management and is the most reliable single source for Indian financial and monetary data.`,
}

export function getNote(name) {
  // Match by exact name
  if (NOTES[name]) return NOTES[name]
  // Match by slug-friendly prefix
  for (const [key, value] of Object.entries(NOTES)) {
    if (name.toLowerCase().includes(key.toLowerCase())) return value
  }
  return null
}
